package cmd

import (
	"log"
	"os"

	"github.com/bwmarrin/discordgo"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

var logFile string

func init() {
	rootCmd.PersistentFlags().StringVarP(&logFile, "file", "f", "", "path to the log file")
	rootCmd.MarkFlagRequired("file")
}

var rootCmd = &cobra.Command{
	Use:   "woblog",
	Short: "parse the logs generated by wobbotfet",
}

func Execute() {
	if err := rootCmd.Execute(); err != nil {
		log.Println(err)
		os.Exit(1)
	}
}

var discord *discordgo.Session

func session() *discordgo.Session {
	if discord != nil {
		return discord
	}
	viper.SetConfigName("config")
	viper.AddConfigPath("..")
	viper.AddConfigPath(".")
	if err := viper.ReadInConfig(); err != nil {
		log.Fatal(err)
	}
	var err error
	discord, err = discordgo.New("Bot " + viper.GetString("token.prod")) // TODO?
	if err != nil {
		log.Fatal(err)
	}
	err = discord.Open()
	if err != nil {
		log.Fatal(err)
	}
	return discord
}
