name: Build
on:
    create:
        tags:
            - v2.*

jobs:
    debug:
        name: Debug
        runs-on: ubuntu-latest
        steps:
            - name: Dump env
              run: env | sort
            - name: Dump github
              env:
                  GITHUB_CONTECT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"

    build:
        name: go build
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v1
              with:
                  fetch-depth: 1

            - name: build
              run: docker build -t ${{ secrets.DOCKER_USERNAME }}/wobbotfet:${{github.ref}} v2

            - name: push to DockerHub
              uses: azure/docker-login@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - run: docker push ${{ secrets.DOCKER_USERNAME }}/wobbotfet:${{github.ref}}
